export const newEventTypes = {
    GET_ALL_EVENTS: 'GET_ALL_EVENTS',
    GET_ERR_MESSAGE: 'GET_ERR_MESSAGE',
    UPDATE_AUTHOR_ID: 'UPDATE_AUTHOR_ID',
    UPDATE_CURRENT_EVENT: 'UPDATE_CURRENT_EVENT',
    UPDATE_EVENT_DESCRIPTION: 'UPDATE_EVENT_DESCRIPTION',
    UPDATE_EVENT_END_DATE: 'UPDATE_EVENT_END_DATE',
    UPDATE_EVENT_END_TIME: 'UPDATE_EVENT_END_TIME',
    UPDATE_EVENT_LOCATION: 'UPDATE_EVENT_LOCATION',
    UPDATE_EVENT_NAME: 'UPDATE_EVENT_NAME',
    UPDATE_EVENT_START_DATE: 'UPDATE_EVENT_START_DATE',
    UPDATE_EVENT_START_TIME: 'UPDATE_EVENT_START_TIME',
    UPDATE_EVENT_TYPE: 'UPDATE_EVENT_TYPE',
    UPDATE_EVENT_VISIBILITY: 'UPDATE_EVENT_VISIBILITY',
    UPDATE_SHOW_MODAL: 'UPDATE_SHOW_MODAL'
}