export const newUserTypes = {
    UPDATE_AGE: 'UPDATE_AGE',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_FIRSTNAME: 'UPDATE_FIRSTNAME',
    UPDATE_LASTNAME: 'UPDATE_LASTNAME',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_USERNAME: 'UPDATE_USERNAME'
}